USE [NewsArticleRepositoryDb]
GO

/****** Object:  Table [dbo].[ImageType]    Script Date: 16/06/2018 16:52:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ImageType](
	[ImageTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](20) NOT NULL,
	 CONSTRAINT [PK_ImageType] PRIMARY KEY CLUSTERED 
	(
		[Type]
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO