USE [master]
GO
	ALTER DATABASE [NewsArticleRepositoryDb] SET COMPATIBILITY_LEVEL = 140
	GO

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [NewsArticleRepositoryDb].[dbo].[sp_fulltext_database] @action = 'enable'
	end
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ANSI_NULL_DEFAULT OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ANSI_NULLS OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ANSI_PADDING OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ANSI_WARNINGS OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ARITHABORT OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET AUTO_CLOSE OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET AUTO_SHRINK OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET AUTO_UPDATE_STATISTICS ON 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET CURSOR_DEFAULT  GLOBAL 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET CONCAT_NULL_YIELDS_NULL OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET NUMERIC_ROUNDABORT OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET QUOTED_IDENTIFIER OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET RECURSIVE_TRIGGERS OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET  DISABLE_BROKER 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET TRUSTWORTHY OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET PARAMETERIZATION SIMPLE 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET READ_COMMITTED_SNAPSHOT OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET HONOR_BROKER_PRIORITY OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET RECOVERY SIMPLE 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET  MULTI_USER 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET PAGE_VERIFY CHECKSUM  
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET DB_CHAINING OFF 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET DELAYED_DURABILITY = DISABLED 
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET QUERY_STORE = OFF
	GO

USE [NewsArticleRepositoryDb]
GO

	ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
	GO

	ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
	GO

	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
	GO

	ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
	GO

	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
	GO

	ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
	GO

	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
	GO

	ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
	GO

	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
	GO

	ALTER DATABASE [NewsArticleRepositoryDb] SET  READ_WRITE 
	GO

